2022-05-19 01:12:17,910 [ERROR] _handle_response (async_http.py:55): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, error: 401, 返回内容: {"message":"wrong bot token","code":11242}, trace_id:8e375d6cdbc65d52ccd0cdaa7beda232
2022-05-19 01:42:34,595 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-19 01:42:34,596 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-19 01:42:34,596 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-19 01:42:34,596 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-19 01:42:34,906 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-19 01:42:34,907 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-19 01:42:35,002 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-19 01:42:35,003 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-19 01:42:58,040 [INFO] _message_handler (robot.py:25): event <qqbot.model.ws_context.WsContext object at 0x0000014999A2C8E0>,receive message <@!18246795234464775126> 
2022-05-19 01:53:22,820 [INFO] _message_handler (robot.py:25): event <qqbot.model.ws_context.WsContext object at 0x0000014999A4C460>,receive message <@!18246795234464775126> 
2022-05-19 02:12:34,911 [INFO] on_close (ws_async_client.py:39): [ws连接]关闭, 返回码: 4009, 返回信息:Session timed out
2022-05-19 02:12:34,919 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-19 02:12:34,919 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-19 02:12:34,919 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-19 02:12:35,388 [INFO] reconnect (ws_async_client.py:146): [ws连接]重连启动...
2022-05-19 02:12:35,389 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-19 02:42:35,344 [INFO] on_close (ws_async_client.py:39): [ws连接]关闭, 返回码: 4009, 返回信息:Session timed out
2022-05-19 02:42:35,345 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-19 02:42:35,345 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-19 02:42:35,345 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-19 02:42:35,765 [INFO] reconnect (ws_async_client.py:146): [ws连接]重连启动...
2022-05-19 02:42:35,765 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-19 03:12:35,733 [INFO] on_close (ws_async_client.py:39): [ws连接]关闭, 返回码: 4009, 返回信息:Session timed out
2022-05-19 03:12:35,734 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-19 03:12:35,734 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-19 03:12:35,735 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-19 03:12:36,306 [INFO] reconnect (ws_async_client.py:146): [ws连接]重连启动...
2022-05-19 03:12:36,306 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-19 03:20:57,894 [INFO] on_close (ws_async_client.py:39): [ws连接]关闭, 返回码: 1006, 返回信息:None
2022-05-19 03:20:57,894 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-19 03:20:57,894 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-19 03:20:57,894 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-19 03:21:09,190 [ERROR] on_error (ws_async_client.py:32): on_error: websocket connection: None, exception : Cannot connect to host api.sgroup.qq.com:443 ssl:default [getaddrinfo failed]
